{{ if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-tools.fullname" . }}-credentials
  labels:
    {{- include "db-tools.labels" . | nindent 4 }}
type: Opaque
data:
    username : {{ .Values.credentials.username | b64enc | quote}}
    password : {{ .Values.credentials.password | b64enc | quote}}
    superadmin_password: {{ .Values.credentials.sa_password | b64enc | quote}}
{{ end }}
